print ("Hello..., Good Evening Cunts!....")
print ("But Don't you worry,  DADDY'S HOME.......!")
print ("By the Way!, You are all Fucking Welcome......!")
print ("Hello! My name is Soldier Boy... Fuck! The WHole world knows Who Iam Why do I have to say it?")
print ("Why So Serious?")
print ("I AM IRON MAN")
print ("Name's Butcher... Billy Butcher!")
print ("SAY MY NAME!")
print ("You are God Dam Right!")
print ("John wick is a man of Sheer Fucking will")
print ("Choices have consequences")
print ("Are you ready John?.......    Yeaaahhh.....!")
print ("My name is Gustavo, but you can call me Gus")
print ("Hardest choices require the strongest wills")
print ("Wise words Captain")
